"""postprocess — Wall and Wall-attached object placement."""

import os
import json
import glob
import argparse
import numpy as np


# ── Geometry helpers ──────────────────────────────────────────────────────────

def load_obj_verts(path: str) -> np.ndarray:
    verts = []
    with open(path) as f:
        for line in f:
            if line.startswith("v "):
                p = line.split()
                verts.append([float(p[1]), float(p[2]), float(p[3])])
    return np.array(verts, dtype=np.float32) if verts else np.zeros((0, 3), dtype=np.float32)


def quat_to_rotmat(q):
    x, y, z, w = float(q[0]), float(q[1]), float(q[2]), float(q[3])
    return np.array([
        [1 - 2*(y*y + z*z),   2*(x*y - z*w),     2*(x*z + y*w)],
        [    2*(x*y + z*w), 1 - 2*(x*x + z*z),   2*(y*z - x*w)],
        [    2*(x*z - y*w),     2*(y*z + x*w), 1 - 2*(x*x + y*y)],
    ], dtype=np.float64)


def quat_mul(q1, q2):
    x1, y1, z1, w1 = float(q1[0]), float(q1[1]), float(q1[2]), float(q1[3])
    x2, y2, z2, w2 = float(q2[0]), float(q2[1]), float(q2[2]), float(q2[3])
    return np.array([
        w1*x2 + x1*w2 + y1*z2 - z1*y2,
        w1*y2 - x1*z2 + y1*w2 + z1*x2,
        w1*z2 + x1*y2 - y1*x2 + z1*w2,
        w1*w2 - x1*x2 - y1*y2 - z1*z2,
    ], dtype=np.float64)


def quat_from_yaw(yaw: float) -> np.ndarray:
    return np.array([0.0, np.sin(yaw * 0.5), 0.0, np.cos(yaw * 0.5)], dtype=np.float64)



def transform_verts(verts: np.ndarray, pos, rot_xyzw) -> np.ndarray:
    R = quat_to_rotmat(rot_xyzw)
    return (R @ verts.T).T + np.array(pos)


# ── OBJ writing helpers ───────────────────────────────────────────────────────

def make_wall_obj(v0, v1, normal_axis: int, pos_along_normal: float,
                  y_range, out_path: str, outward_sign: int = 1):
    thickness = 0.01 * outward_sign
    y0, y1 = y_range
    corners = [
        [v0, y0, pos_along_normal],
        [v1, y0, pos_along_normal],
        [v1, y1, pos_along_normal],
        [v0, y1, pos_along_normal],
    ]
    back_corners = [[c[0], c[1], c[2] + thickness] for c in corners]

    def reorder(c):
        if normal_axis == 0:
            return [c[2], c[1], c[0]]
        return c

    all_verts = [reorder(c) for c in corners] + [reorder(c) for c in back_corners]
    if outward_sign >= 0:
        faces = [[1,2,3,4],[8,7,6,5],[1,2,6,5],[4,3,7,8],[1,5,8,4],[2,6,7,3]]
    else:
        faces = [[4,3,2,1],[5,6,7,8],[5,6,2,1],[8,7,3,4],[4,8,5,1],[3,7,6,2]]
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write("# Wall mesh generated by postprocess.py\n")
        for v in all_verts:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
        for fc in faces:
            f.write("f " + " ".join(str(i) for i in fc) + "\n")


def make_wall_obj_oriented(p0_xz, p1_xz, outward_n_xz, y_range, out_path: str):
    thickness = 0.01
    y0, y1 = y_range
    p0 = np.array(p0_xz, dtype=np.float64)
    p1 = np.array(p1_xz, dtype=np.float64)
    n  = np.array(outward_n_xz, dtype=np.float64)
    n  = n / max(1e-12, np.linalg.norm(n))
    t  = thickness * n
    front = [[p0[0],y0,p0[1]],[p1[0],y0,p1[1]],[p1[0],y1,p1[1]],[p0[0],y1,p0[1]]]
    back  = [[p0[0]+t[0],y0,p0[1]+t[1]],[p1[0]+t[0],y0,p1[1]+t[1]],
             [p1[0]+t[0],y1,p1[1]+t[1]],[p0[0]+t[0],y1,p0[1]+t[1]]]
    all_verts = front + back
    faces = [[1,2,3,4],[8,7,6,5],[1,2,6,5],[4,3,7,8],[1,5,8,4],[2,6,7,3]]
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write("# Oriented wall mesh generated by postprocess.py\n")
        for v in all_verts:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
        for fc in faces:
            f.write("f " + " ".join(str(i) for i in fc) + "\n")


def export_transformed_obj(src_path: str, pos, rot_xyzw, out_path: str):
    R = quat_to_rotmat(rot_xyzw)
    lines_out = []
    with open(src_path) as f:
        for line in f:
            if line.startswith("v "):
                p = line.split()
                v = np.array([float(p[1]), float(p[2]), float(p[3])])
                vw = R @ v + np.array(pos)
                extra = (" " + " ".join(p[4:])) if len(p) > 4 else ""
                lines_out.append(f"v {vw[0]:.6f} {vw[1]:.6f} {vw[2]:.6f}{extra}\n")
            else:
                lines_out.append(line)
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.writelines(lines_out)


# ── Scene-tree helpers ────────────────────────────────────────────────────────

def parse_scene_tree(tree_path: str):
    tree = json.load(open(tree_path))
    parent_of = {}
    type_of   = {}
    for e in tree["edges"]:
        parent_of[e["child"]] = e["parent"]
        type_of[e["child"]]   = e["type"]
    return parent_of, type_of


def detect_file_prefix(obj_dir: str, sample_name: str) -> str:
    for fname in os.listdir(obj_dir):
        if fname.endswith(f"{sample_name}.obj"):
            return fname[: -len(f"{sample_name}.obj")]
    return ""


# ── Constants ─────────────────────────────────────────────────────────────────

WALL_MARGIN              = 0.02
SIDE_WALL_MARGIN         = 0.10
WALL_OBJ_INSET           = 0.05
ROOM_HEIGHT_EXTRA        = 0.10
WALL_OBJ_HEIGHT_EXTRA    = 0.10
WALL_YAW_ALIGN_SKIP_SPREAD = 0.09
WALL_YAW_ALIGN_NAME_KEYS = (
    "basket", "woven", "curtain", "garland", "wreath", "macrame", "tapestry",
)
ANTI_PEN_BACK_MAX_SHIFT  = 0.18


# ── Core geometry helpers ─────────────────────────────────────────────────────

def _convex_hull_xz_points(xy: np.ndarray) -> np.ndarray:
    if xy.shape[0] < 3:
        return xy
    rnd  = np.round(xy.astype(np.float64), decimals=5)
    xy_u = np.unique(rnd, axis=0)
    if xy_u.shape[0] < 3:
        return xy_u
    order = np.lexsort((xy_u[:, 1], xy_u[:, 0]))
    pts   = xy_u[order]

    def cross(o, a, b):
        return (a[0]-o[0])*(b[1]-o[1]) - (a[1]-o[1])*(b[0]-o[0])

    lower = []
    for p in pts:
        while len(lower) >= 2 and cross(lower[-2], lower[-1], p) <= 0:
            lower.pop()
        lower.append(tuple(p))
    upper = []
    for p in reversed(pts):
        while len(upper) >= 2 and cross(upper[-2], upper[-1], p) <= 0:
            upper.pop()
        upper.append(tuple(p))
    return np.array(lower[:-1] + upper[:-1], dtype=np.float64)


def _wall_depth_ref_xz(xz: np.ndarray, plane_p: np.ndarray, plane_inward: np.ndarray,
                       policy: str) -> float:
    if policy == "min":
        return float(((xz - plane_p[None, :]) @ plane_inward).min())
    if policy == "hull_aabb":
        n    = xz.shape[0]
        xz_s = xz[:: max(1, n // 5000)] if n > 5000 else xz
        hull  = _convex_hull_xz_points(xz_s.astype(np.float64))
        d_hull = (hull - plane_p) @ plane_inward
        lo = xz.min(axis=0); hi = xz.max(axis=0)
        corners = np.array([[lo[0],lo[1]],[lo[0],hi[1]],[hi[0],lo[1]],[hi[0],hi[1]]], dtype=np.float64)
        d_box   = (corners - plane_p) @ plane_inward
        return float(min(d_hull.min(), d_box.min()))
    if policy == "max":
        return float(((xz - plane_p[None, :]) @ plane_inward).max())
    raise ValueError(f"unknown wall depth policy {policy!r}")


def determine_primary_wall(floor_wall_names, wall_names, world_aabbs, scene_min, scene_max):
    valid_fw   = [n for n in floor_wall_names if n in world_aabbs]
    valid_wall = [n for n in wall_names       if n in world_aabbs]

    def _footprint(name):
        lo, hi = world_aabbs[name]
        return max(1e-6, float((hi[0]-lo[0])*(hi[2]-lo[2])))

    def _face_gaps(name):
        lo, hi = world_aabbs[name]
        return {
            "X_min": float(lo[0]-scene_min[0]),
            "X_max": float(scene_max[0]-hi[0]),
            "Z_min": float(lo[2]-scene_min[2]),
            "Z_max": float(scene_max[2]-hi[2]),
        }

    def _label_to_axis_side(label):
        return {"X_min":(0,False),"X_max":(0,True),"Z_min":(2,False),"Z_max":(2,True)}[label]

    if valid_fw:
        fw_votes  = {"X_min":0.0,"X_max":0.0,"Z_min":0.0,"Z_max":0.0}
        fw_groups = {k:[] for k in fw_votes}
        for n in valid_fw:
            gaps = _face_gaps(n)
            best = min(gaps, key=gaps.get)
            w    = _footprint(n)
            fw_votes[best]  += w
            fw_groups[best].append((n, gaps[best], w))
            print(f"  [WallDetect/fw] {n}: X_min={gaps['X_min']:.3f} X_max={gaps['X_max']:.3f} "
                  f"Z_min={gaps['Z_min']:.3f} Z_max={gaps['Z_max']:.3f} -> {best} (w={w:.3f})")

        aux_votes = {"X_min":0.0,"X_max":0.0,"Z_min":0.0,"Z_max":0.0}
        for n in valid_wall:
            gaps = _face_gaps(n)
            best = min(gaps, key=gaps.get)
            aux_votes[best] += 0.25 * _footprint(n)

        total_votes = {k: fw_votes[k]+aux_votes[k] for k in fw_votes}
        print("  [WallDetect/vote] floor-wall:", "  ".join(f"{k}={v:.3f}" for k,v in total_votes.items()))

        best_vote = max(total_votes.values())
        cand = [k for k,v in total_votes.items() if abs(v-best_vote) < 1e-8]
        if len(cand) == 1:
            chosen = cand[0]
        else:
            def _mean_gap(label):
                grp = fw_groups[label]
                if not grp: return 1e9
                ws = np.array([x[2] for x in grp]); gs = np.array([x[1] for x in grp])
                return float((ws*gs).sum() / max(1e-9, ws.sum()))
            chosen = min(cand, key=_mean_gap)
            print(f"  [WallDetect/vote] tie {cand} -> choose {chosen} by mean-gap")

        normal_axis, at_max_side = _label_to_axis_side(chosen)
        anchors = [n for (n,_,_) in fw_groups[chosen]] or valid_fw
        if at_max_side:
            back_face = max(world_aabbs[n][1][normal_axis] for n in anchors)
            back_wall_pos = back_face + WALL_MARGIN
        else:
            back_face = min(world_aabbs[n][0][normal_axis] for n in anchors)
            back_wall_pos = back_face - WALL_MARGIN
        print(f"  [WallDetect] chosen={chosen}  anchors={anchors}  "
              f"back_face={back_face:.4f}  back_wall_pos={back_wall_pos:.4f}")
        return normal_axis, at_max_side, back_wall_pos

    if not valid_wall:
        return 2, True, scene_max[2] + WALL_MARGIN

    candidates = [(0,True,scene_max[0]),(0,False,scene_min[0]),(2,True,scene_max[2]),(2,False,scene_min[2])]
    scores = {}
    for (axis, at_max, bound) in candidates:
        gaps = [abs((world_aabbs[n][1][axis] if at_max else world_aabbs[n][0][axis]) - bound) for n in valid_wall]
        scores[(axis, at_max)] = np.mean(gaps)
    best = min(scores, key=scores.get)
    normal_axis, at_max_side = best
    extents = [world_aabbs[n][1][normal_axis] if at_max_side else world_aabbs[n][0][normal_axis] for n in valid_wall]
    back_face = max(extents) if at_max_side else min(extents)
    back_wall_pos = back_face + WALL_MARGIN if at_max_side else back_face - WALL_MARGIN
    return normal_axis, at_max_side, back_wall_pos


def compute_perp_wall_positions(floor_wall_names, wall_names, world_aabbs,
                                perp_axis, scene_min, scene_max):
    SNAP_DIST = 0.30
    combined  = list({n for n in (floor_wall_names+wall_names) if n in world_aabbs})

    at_max = [n for n in combined if (scene_max[perp_axis]-world_aabbs[n][1][perp_axis]) <= SNAP_DIST]
    side_max_pos = (max(world_aabbs[n][1][perp_axis] for n in at_max) + WALL_MARGIN
                    if at_max else scene_max[perp_axis] + SIDE_WALL_MARGIN)

    at_min = [n for n in combined if (world_aabbs[n][0][perp_axis]-scene_min[perp_axis]) <= SNAP_DIST]
    side_min_pos = (min(world_aabbs[n][0][perp_axis] for n in at_min) - WALL_MARGIN
                    if at_min else scene_min[perp_axis] - SIDE_WALL_MARGIN)

    return side_min_pos, side_max_pos


def assign_wall_objects_to_walls(wall_names, world_aabbs, normal_axis, at_max_side,
                                  back_wall_pos, side_min_pos, side_max_pos,
                                  front_wall_pos=None) -> dict:
    SNAP_DIST               = 0.05
    CLUSTER_DIST            = 0.80
    SNAP_MAX_DEPTH_FOR_BACK = SNAP_DIST * 4
    SNAP_SIDE_CENTROID_RATIO = 8.0
    SNAP_SIDE_CENTROID_MIN   = 0.12

    perp_axis = 2 if normal_axis == 0 else 0
    valid     = [n for n in wall_names if n in world_aabbs]
    assignments: dict = {}

    def _gap_back(lo, hi):
        return abs(back_wall_pos - (hi[normal_axis] if at_max_side else lo[normal_axis]))
    def _gap_side_mn(lo, hi):
        return abs(lo[perp_axis] - side_min_pos)
    def _gap_side_mx(lo, hi):
        return abs(hi[perp_axis] - side_max_pos)
    def _gap_front(lo, hi):
        return abs(front_wall_pos - (lo[normal_axis] if at_max_side else hi[normal_axis]))

    remaining = []
    for name in valid:
        lo, hi = world_aabbs[name]
        gaps = {"back": _gap_back(lo,hi), "side_min": _gap_side_mn(lo,hi), "side_max": _gap_side_mx(lo,hi)}
        if front_wall_pos is not None:
            gaps["front"] = _gap_front(lo, hi)
        best_wall, best_gap = min(gaps.items(), key=lambda kv: kv[1])
        if best_gap < SNAP_DIST:
            if best_wall == "back":
                if (hi[normal_axis]-lo[normal_axis]) > SNAP_MAX_DEPTH_FOR_BACK:
                    remaining.append(name); continue
            if best_wall in ("side_min", "side_max"):
                centroid = (lo+hi)/2.0
                cen_gap = abs(centroid[perp_axis] - (side_min_pos if best_wall=="side_min" else side_max_pos))
                if cen_gap > best_gap*SNAP_SIDE_CENTROID_RATIO and cen_gap > SNAP_SIDE_CENTROID_MIN:
                    remaining.append(name); continue
            if best_wall == "front" and front_wall_pos is not None:
                centroid = (lo+hi)/2.0
                cen_gap_front = abs(front_wall_pos - centroid[normal_axis])
                if cen_gap_front > best_gap*SNAP_SIDE_CENTROID_RATIO and cen_gap_front > SNAP_SIDE_CENTROID_MIN:
                    remaining.append(name); continue
            assignments[name] = best_wall
            print(f"  [Assign/snap] {name} -> {best_wall}  gap={best_gap:.4f}")
        else:
            remaining.append(name)

    if not remaining:
        return assignments

    centroids = {n: (world_aabbs[n][0]+world_aabbs[n][1])/2.0 for n in remaining}
    clusters: list = []
    used: set = set()
    for seed in remaining:
        if seed in used: continue
        cluster = [seed]; used.add(seed)
        for other in remaining:
            if other in used: continue
            if np.linalg.norm(centroids[seed]-centroids[other]) < CLUSTER_DIST:
                cluster.append(other); used.add(other)
        clusters.append(cluster)

    for cluster in clusters:
        all_lo = np.array([world_aabbs[n][0] for n in cluster])
        all_hi = np.array([world_aabbs[n][1] for n in cluster])
        clo = all_lo.min(axis=0); chi = all_hi.max(axis=0)

        _cen_n = 0.5*(clo[normal_axis]+chi[normal_axis])
        _cen_p = 0.5*(clo[perp_axis]+chi[perp_axis])
        gaps_cen = {"back": abs(back_wall_pos-_cen_n), "side_min": abs(_cen_p-side_min_pos),
                    "side_max": abs(_cen_p-side_max_pos)}
        if front_wall_pos is not None:
            gaps_cen["front"] = abs(front_wall_pos-_cen_n)
        gaps_face = {"back": _gap_back(clo,chi), "side_min": _gap_side_mn(clo,chi),
                     "side_max": _gap_side_mx(clo,chi)}
        if front_wall_pos is not None:
            gaps_face["front"] = _gap_front(clo, chi)
        gaps_eff = {}
        for w in gaps_cen:
            if w in ("back", "front"):
                gaps_eff[w] = min(float(gaps_cen[w]), float(gaps_face[w]))
            else:
                gaps_eff[w] = float(gaps_cen[w])

        depth_n = float(chi[normal_axis]-clo[normal_axis])
        depth_p = float(chi[perp_axis]-clo[perp_axis])
        SLAB_RATIO = 0.86
        if depth_n+1e-9 < depth_p*SLAB_RATIO:
            pool = {k: gaps_eff[k] for k in ("back","front") if k in gaps_eff}
            wall_label = min(pool, key=pool.get)
        elif depth_p+1e-9 < depth_n*SLAB_RATIO:
            pool = {k: float(gaps_cen[k]) for k in ("side_min","side_max")}
            wall_label = min(pool, key=pool.get)
        else:
            wall_label = min(gaps_eff, key=gaps_eff.get)

        for name in cluster:
            assignments[name] = wall_label
            print(f"  [Assign/centroid] {name} -> {wall_label}")

    return assignments


def compute_world_aabbs(all_names, obj_dir, prefix, poses_dict, base_dy):
    aabbs = {}
    identity_rot = [0.0, 0.0, 0.0, 1.0]
    identity_pos = [0.0, base_dy, 0.0]
    for name in all_names:
        obj_path = os.path.join(obj_dir, f"{prefix}{name}.obj")
        if not os.path.isfile(obj_path):
            continue
        verts = load_obj_verts(obj_path)
        pos, rot = (poses_dict[name]["pos"], poses_dict[name]["rot"]) if name in poses_dict \
                   else (identity_pos, identity_rot)
        vw = transform_verts(verts, pos, rot)
        aabbs[name] = (vw.min(axis=0), vw.max(axis=0))
    return aabbs


def compute_world_geometry(all_names, obj_dir, prefix, poses_dict, base_dy):
    aabbs = {}; clouds = {}
    identity_rot = [0.0, 0.0, 0.0, 1.0]
    identity_pos = [0.0, base_dy, 0.0]
    for name in all_names:
        obj_path = os.path.join(obj_dir, f"{prefix}{name}.obj")
        if not os.path.isfile(obj_path): continue
        verts = load_obj_verts(obj_path)
        pos, rot = (poses_dict[name]["pos"], poses_dict[name]["rot"]) if name in poses_dict \
                   else (identity_pos, identity_rot)
        vw = transform_verts(verts, pos, rot)
        clouds[name] = vw
        aabbs[name]  = (vw.min(axis=0), vw.max(axis=0))
    return aabbs, clouds


def estimate_room_frame_from_floor_wall(floor_wall_names, clouds, scene_min=None, scene_max=None):
    valid = [n for n in floor_wall_names if n in clouds]
    if not valid:
        return None, None, None

    KEYWORDS = ("cabinet", "wardrobe", "bookcase", "closet", "shelf", "counter")
    kw_hits = [n for n in valid if any(k in n.lower() for k in KEYWORDS)]

    def _area(name):
        pts = clouds[name][:, [0,2]]; lo=pts.min(axis=0); hi=pts.max(axis=0)
        return float((hi[0]-lo[0])*(hi[1]-lo[1]))

    def _wall_proximity_score(name):
        pts = clouds[name][:, [0,2]]; c = pts.mean(axis=0); q = pts-c
        cov = (q.T @ q) / max(1, q.shape[0])
        evals, evecs = np.linalg.eigh(cov)
        short_ev = evecs[:, int(np.argmin(evals))]
        d = pts @ short_ev
        obj_lo_d, obj_hi_d = float(d.min()), float(d.max())
        corners_xz = np.array([[scene_min[0],scene_min[2]],[scene_min[0],scene_max[2]],
                                [scene_max[0],scene_min[2]],[scene_max[0],scene_max[2]]], dtype=np.float64)
        d_scene = corners_xz @ short_ev
        s_lo, s_hi = float(d_scene.min()), float(d_scene.max())
        gap = min(abs(obj_lo_d-s_lo), abs(obj_hi_d-s_hi))
        aspect = float(evals[-1]) / max(1e-9, float(evals[0]))
        return aspect / max(1e-6, gap)

    anchor_pool = kw_hits if kw_hits else valid
    if scene_min is not None and scene_max is not None:
        anchor = max(anchor_pool, key=_wall_proximity_score)
    else:
        anchor = max(anchor_pool, key=_area)

    pts = clouds[anchor][:, [0,2]]; c = pts.mean(axis=0); q = pts-c
    cov = (q.T @ q) / max(1, q.shape[0])
    evals, evecs = np.linalg.eigh(cov)
    u = evecs[:, int(np.argmax(evals))]
    u = u / max(1e-12, np.linalg.norm(u))
    if (u[0] < 0) or (abs(u[0]) < 1e-9 and u[1] < 0):
        u = -u
    n = np.array([-u[1], u[0]], dtype=np.float64)
    print(f"  [Frame] anchor={anchor}")
    return anchor, u, n


def estimate_room_frame_from_major_floor_voters(parent_of, clouds, robust_names):
    KEYWORDS = ("sofa","couch","bed","cabinet","wardrobe","bookcase","closet","shelf",
                "desk","table","refrigerator","fridge")
    robust_set  = set(robust_names)
    candidates  = [n for n in robust_set if parent_of.get(n)=="floor" and n in clouds]
    if not candidates:
        return None, None, None

    def _area(name):
        pts = clouds[name][:,[0,2]]; lo=pts.min(axis=0); hi=pts.max(axis=0)
        return float(max(1e-6,(hi[0]-lo[0])*(hi[1]-lo[1])))
    def _boost(name):
        return 2.5 if any(k in name.lower() for k in KEYWORDS) else 1.0

    scores = {n: _area(n)*_boost(n) for n in candidates}
    best   = max(scores.values()) if scores else 0.0
    if best <= 0.0: return None, None, None
    voters = [n for n in candidates if scores[n] >= 0.35*best] or [max(candidates, key=lambda x: scores[x])]

    c2 = 0.0; s2 = 0.0
    for n in voters:
        t = estimate_tangent_from_cloud_xz(clouds[n])
        w = scores[n]; ang = float(np.arctan2(t[1],t[0]))
        c2 += w*np.cos(2.0*ang); s2 += w*np.sin(2.0*ang)

    theta = 0.5 * float(np.arctan2(s2, c2))
    u = np.array([np.cos(theta), np.sin(theta)], dtype=np.float64)
    u = u / max(1e-12, np.linalg.norm(u))
    if (u[0] < 0) or (abs(u[0]) < 1e-9 and u[1] < 0):
        u = -u
    n = np.array([-u[1], u[0]], dtype=np.float64)
    print(f"  [Frame] source=major_floor_voters  voters={voters}")
    return voters, u, n


SEATING_FRAME_KEYWORDS = ("sofa","couch","sectional","loveseat","settee")


def _xz_footprint_area(cloud: np.ndarray) -> float:
    pts = cloud[:,[0,2]]; lo=pts.min(axis=0); hi=pts.max(axis=0)
    return float(max(0.0,(hi[0]-lo[0])*(hi[1]-lo[1])))


def _longest_hull_edge_tangent_xz(vw: np.ndarray):
    pts  = vw[:,[0,2]].astype(np.float64)
    if pts.shape[0] < 2: return None, []
    hull = _convex_hull_xz_points(pts)
    if hull.shape[0] < 2: return None, []
    best_t = None; best_len = 0.0; lens = []
    nh = hull.shape[0]
    for i in range(nh):
        e = hull[(i+1)%nh]-hull[i]; le = float(np.linalg.norm(e)); lens.append(le)
        if le > best_len:
            best_len = le; best_t = e/le
    if best_t is None: return None, lens
    if (best_t[0] < 0) or (abs(best_t[0]) < 1e-9 and best_t[1] < 0):
        best_t = -best_t
    return best_t, sorted(lens, reverse=True)[:5]


def estimate_tangent_longest_hull_edge_xz(vw: np.ndarray) -> np.ndarray:
    t, _ = _longest_hull_edge_tangent_xz(vw)
    return t if t is not None else estimate_tangent_from_cloud_xz(vw)


def estimate_tangent_hull_perp_to_opening_xz(vw: np.ndarray, scene_center_xz: np.ndarray,
                                              min_len_frac: float = 0.28) -> np.ndarray:
    pts  = vw[:,[0,2]].astype(np.float64); c = pts.mean(axis=0)
    to_room = np.asarray(scene_center_xz, dtype=np.float64).reshape(2) - c
    nl = float(np.linalg.norm(to_room))
    if nl < 1e-5: return estimate_tangent_longest_hull_edge_xz(vw)
    n_open = to_room/nl
    hull = _convex_hull_xz_points(pts)
    if hull.shape[0] < 2: return estimate_tangent_from_cloud_xz(vw)
    nh = hull.shape[0]
    elens = [float(np.linalg.norm(hull[(i+1)%nh]-hull[i])) for i in range(nh)]
    max_len = max(elens) if elens else 0.0
    min_len = min_len_frac * max_len if max_len > 1e-9 else 0.0
    best_score = -1.0; best_le = 0.0; best_t = None
    for i in range(nh):
        le = elens[i]
        if le < min_len: continue
        e = hull[(i+1)%nh]-hull[i]; raw_t = e/max(1e-12,le)
        ad = float(abs(np.dot(raw_t, n_open)))
        score = le * float(np.sqrt(max(0.0, 1.0-ad*ad)))
        if score > best_score+1e-12:
            best_score=score; best_le=le; best_t=raw_t.copy()
        elif abs(score-best_score) <= 1e-12 and le > best_le:
            best_le=le; best_t=raw_t.copy()
    if best_t is None: return estimate_tangent_longest_hull_edge_xz(vw)
    if (best_t[0] < 0) or (abs(best_t[0]) < 1e-9 and best_t[1] < 0):
        best_t = -best_t
    return best_t


def maybe_align_frame_to_primary_seating(parent_of, clouds, robust_names, u_xz, n_xz,
                                          anchor_label, anchor_name_for_area=None,
                                          min_seat_area_m2=0.55, min_angle_deg=6.0,
                                          seating_area_vs_anchor_ratio=1.12, scene_center_xz=None):
    candidates = [n for n in robust_names if n in clouds and parent_of.get(n)=="floor"
                  and any(k in n.lower() for k in SEATING_FRAME_KEYWORDS)]
    if not candidates: return u_xz, n_xz, None
    seat = max(candidates, key=lambda n: _xz_footprint_area(clouds[n]))
    area = _xz_footprint_area(clouds[seat])
    if area < min_seat_area_m2:
        return u_xz, n_xz, None

    _vc = clouds[seat]
    u_s = (estimate_tangent_hull_perp_to_opening_xz(_vc, scene_center_xz)
           if scene_center_xz is not None else None)
    u_s = u_s if u_s is not None else estimate_tangent_longest_hull_edge_xz(_vc)
    u_s = u_s / max(1e-12, np.linalg.norm(u_s))
    if (u_s[0] < 0) or (abs(u_s[0]) < 1e-9 and u_s[1] < 0): u_s = -u_s
    n_s = np.array([-u_s[1], u_s[0]], dtype=np.float64)

    cos_al  = float(np.clip(np.dot(u_xz, u_s), -1.0, 1.0))
    ang_deg = float(np.degrees(np.arccos(cos_al)))

    if ang_deg < min_angle_deg:
        cab_a = _xz_footprint_area(clouds[anchor_name_for_area]) \
                if anchor_name_for_area and anchor_name_for_area in clouds else 0.0
        if cab_a > 1e-6 and area >= seating_area_vs_anchor_ratio*cab_a and area >= min_seat_area_m2:
            return u_s, n_s, seat
        return u_xz, n_xz, None

    print(f"  [Frame/seating] OVERRIDE from '{seat}' (area={area:.3f}): angle={ang_deg:.1f}deg")
    return u_s, n_s, seat


def build_local_aabbs_from_frame(clouds, u_xz, n_xz):
    local = {}
    for name, vw in clouds.items():
        xz = vw[:,[0,2]]; u=xz@u_xz; v=xz@n_xz; y=vw[:,1]
        lo = np.array([u.min(), y.min(), v.min()], dtype=np.float64)
        hi = np.array([u.max(), y.max(), v.max()], dtype=np.float64)
        local[name] = (lo, hi)
    return local


def estimate_tangent_from_cloud_xz(vw: np.ndarray):
    pts = vw[:,[0,2]]; c=pts.mean(axis=0); q=pts-c
    cov = (q.T @ q) / max(1, q.shape[0])
    evals, evecs = np.linalg.eigh(cov)
    t = evecs[:, int(np.argmax(evals))]
    return t / max(1e-12, np.linalg.norm(t))


def estimate_normal_from_cloud_xz(vw: np.ndarray):
    pts = vw[:,[0,2]]; c=pts.mean(axis=0); q=pts-c
    cov = (q.T @ q) / max(1, q.shape[0])
    evals, evecs = np.linalg.eigh(cov)
    n = evecs[:, int(np.argmin(evals))]
    return n / max(1e-12, np.linalg.norm(n))


def transform_cloud_from_pose(local_verts: np.ndarray, pos, rot_xyzw):
    return transform_verts(local_verts, pos, rot_xyzw)


def _skip_wall_yaw_align(name: str, spread_catalog: float) -> bool:
    if spread_catalog > WALL_YAW_ALIGN_SKIP_SPREAD: return True
    return any(k in name.lower() for k in WALL_YAW_ALIGN_NAME_KEYS)


# ── Main entry point ──────────────────────────────────────────────────────────

def run(output_dir: str, root_dir: str, scene_tree_name: str = "scene_tree.json",
        margin: float = WALL_MARGIN, out_json_name: str = None,
        debug_save_obj: bool = False, wall_align_max_yaw_deg: float = 25.0,
        force_three_walls: bool = False,
        poses_path: str = None, poses_data: dict = None,
        local_group_dir: str = None,
        wall_obj_dir: str = None, wall_urdf_dir: str = None):

    # 1. Load data
    _local_group_dir = local_group_dir if local_group_dir is not None else output_dir
    tree_path_1 = os.path.join(os.path.dirname(root_dir), scene_tree_name)
    tree_path_2 = os.path.join(root_dir, scene_tree_name)
    tree_path   = tree_path_1 if os.path.isfile(tree_path_1) else tree_path_2
    obj_dir     = os.path.join(root_dir, "obj_files")

    if poses_data is not None:
        poses_json = poses_data
        print(f"[Load] poses:      (in-memory)")
    else:
        if poses_path is None:
            poses_path = os.path.join(output_dir, "phase2_final_poses.json")
        print(f"[Load] poses:      {poses_path}")
        poses_json = json.load(open(poses_path))
    print(f"[Load] scene_tree: {tree_path}")
    print(f"[Load] obj_dir:    {obj_dir}")

    base_dy    = float(poses_json.get("base_dy", 0.002))
    poses_dict = poses_json["objects"]

    parent_of, type_of = parse_scene_tree(tree_path)

    # Merge Phase-1 per-group best poses for group roots and their children.
    _structural_parents       = {"wall", "ceiling", "floor-wall", "floor"}
    _best_child_poses_lookup  = {}
    for _bp in sorted(glob.glob(os.path.join(_local_group_dir, "best_poses_*.json"))):
        _bp_data = json.load(open(_bp))
        for _bname, _bpose in _bp_data.get("objects", {}).items():
            if _bname not in poses_dict:
                _par = parent_of.get(_bname)
                if _par in _structural_parents:
                    poses_dict[_bname] = _bpose
                else:
                    _best_child_poses_lookup[_bname] = _bpose
    if _best_child_poses_lookup:
        print(f"[BestChildLookup] {len(_best_child_poses_lookup)} wall/ceiling group children: "
              f"{list(_best_child_poses_lookup.keys())}")

    # Load world-space child OBJs from best_p1_g*.obj
    _best_child_obj_paths   = {}
    _best_child_world_verts = {}
    _obj_scan_dir = os.path.join(_local_group_dir, "obj_files") \
        if os.path.isdir(os.path.join(_local_group_dir, "obj_files")) else _local_group_dir
    for _fname in sorted(os.listdir(_obj_scan_dir)):
        if not _fname.endswith(".obj") or not _fname.startswith("local_group_g"): continue
        _parts = _fname.split("_", 3)   # ["local", "group", "g{n}", "{cname}.obj"]
        if len(_parts) < 4: continue
        _cname = _parts[3][:-4]
        _cpar  = parent_of.get(_cname)
        _is_wall_child = (
            _cname in _best_child_poses_lookup or
            (_cpar and _cpar in poses_dict and parent_of.get(_cpar) in {"wall", "ceiling"})
        )
        if _is_wall_child:
            _p = os.path.join(_obj_scan_dir, _fname)
            _best_child_obj_paths[_cname] = _p
            if os.path.isfile(_p):
                _best_child_world_verts[_cname] = load_obj_verts(_p)
    if _best_child_world_verts:
        print(f"[BestChildOBJ] Loaded {len(_best_child_world_verts)} child OBJs")

    sample_name = next(iter(poses_dict))
    prefix      = detect_file_prefix(obj_dir, sample_name)
    print(f"[Load] file prefix: '{prefix}'")

    floor_wall_names = [n for n,p in parent_of.items() if p=="floor-wall"]
    wall_names       = [n for n,p in parent_of.items() if p=="wall"]
    ceiling_names    = [n for n,p in parent_of.items() if p=="ceiling"]
    movable_names    = [n for n,t in type_of.items()   if t=="movable"]

    _curtain_ceiling = [n for n in ceiling_names if "curtain" in n.lower()]
    if _curtain_ceiling:
        print(f"[Scene] curtain reclassified ceiling->wall: {_curtain_ceiling}")
        ceiling_names = [n for n in ceiling_names if n not in _curtain_ceiling]
        wall_names    = wall_names + _curtain_ceiling

    print(f"[Scene] floor-wall: {floor_wall_names}")
    print(f"[Scene] wall:       {wall_names}")
    print(f"[Scene] ceiling:    {ceiling_names}")

    all_names = list(set(list(poses_dict.keys()) + floor_wall_names + wall_names + ceiling_names))

    def _norm_name(s): return s.replace('"', '')
    _extra_fixed = []
    _all_names_set      = set(all_names)
    _all_names_norm_set = {_norm_name(n) for n in _all_names_set}
    _structural_roots   = {"floor","wall","ceiling","floor-wall"}
    try:
        for _fname in sorted(os.listdir(obj_dir)):
            if not _fname.endswith(".obj"): continue
            _n = _fname[len(prefix):][:-4] if (prefix and _fname.startswith(prefix)) else _fname[:-4]
            if _n not in _all_names_set and _n not in _all_names_norm_set and _n not in _structural_roots:
                _extra_fixed.append(_n); _all_names_set.add(_n)
    except FileNotFoundError:
        pass
    if _extra_fixed:
        print(f"[Extra fixed] {len(_extra_fixed)} objects not in scene-tree: {_extra_fixed}")
    all_names = all_names + _extra_fixed

    scene_tree  = json.load(open(tree_path))
    children_of = {}
    for e in scene_tree.get("edges", []):
        children_of.setdefault(e["parent"], []).append(e["child"])

    mesh_local_verts = {}
    for name in all_names:
        obj_path = os.path.join(obj_dir, f"{prefix}{name}.obj")
        if os.path.isfile(obj_path):
            mesh_local_verts[name] = load_obj_verts(obj_path)

    # 2. World-space geometry
    print("[AABB] computing world-space bounding boxes...")
    aabbs, clouds = compute_world_geometry(all_names, obj_dir, prefix, poses_dict, base_dy)

    # 2b. Robust scene AABB (exclude large-residual outliers)
    OUTLIER_POS_THRESHOLD = 0.5
    robust_names = []
    for name in aabbs:
        if name in poses_dict:
            pos_res = np.array(poses_dict[name]["pos"])
            if np.linalg.norm(pos_res) > OUTLIER_POS_THRESHOLD:
                print(f"  [RobustAABB] EXCLUDING {name} (pos_res={np.linalg.norm(pos_res):.3f})")
                continue
        robust_names.append(name)

    robust_lo = np.array([aabbs[n][0] for n in robust_names])
    robust_hi = np.array([aabbs[n][1] for n in robust_names])
    scene_min = robust_lo.min(axis=0)
    scene_max = robust_hi.max(axis=0)
    print(f"[Scene AABB] x=[{scene_min[0]:.3f}~{scene_max[0]:.3f}]  "
          f"y=[{scene_min[1]:.3f}~{scene_max[1]:.3f}]  "
          f"z=[{scene_min[2]:.3f}~{scene_max[2]:.3f}]")

    # 2c. Room height
    _wall_tops = [aabbs[n][1][1] for n in wall_names if n in aabbs]
    if ceiling_names:
        room_height = scene_max[1] + ROOM_HEIGHT_EXTRA
    elif _wall_tops:
        room_height = max(max(_wall_tops)+WALL_OBJ_HEIGHT_EXTRA, scene_max[1]+ROOM_HEIGHT_EXTRA)
    else:
        room_height = scene_max[1] + ROOM_HEIGHT_EXTRA
    y_range = (0.0, room_height)
    print(f"[Room height] {room_height:.3f}")

    front_v_local = None

    # 3. Estimate room frame
    anchor_name, u_xz, n_xz = estimate_room_frame_from_floor_wall(
        floor_wall_names, clouds, scene_min=scene_min, scene_max=scene_max)
    major_voters = None
    if anchor_name is None:
        major_voters, u_xz, n_xz = estimate_room_frame_from_major_floor_voters(
            parent_of, clouds, robust_names)

    if u_xz is not None and n_xz is not None:
        _frame_lbl = anchor_name if anchor_name is not None else "major_voters"
        _scene_center_xz = np.array(
            [(scene_min[0]+scene_max[0])*0.5, (scene_min[2]+scene_max[2])*0.5], dtype=np.float64)
        u_xz, n_xz, _seat_override = maybe_align_frame_to_primary_seating(
            parent_of, clouds, robust_names, u_xz, n_xz, _frame_lbl,
            anchor_name_for_area=anchor_name, scene_center_xz=_scene_center_xz)

    if (anchor_name is not None) or (major_voters is not None):
        local_aabbs = build_local_aabbs_from_frame(clouds, u_xz, n_xz)
        non_wall_robust = [n for n in robust_names if n in local_aabbs and n not in wall_names]
        if not non_wall_robust:
            non_wall_robust = [n for n in robust_names if n in local_aabbs]
        robust_lo_local = np.array([local_aabbs[n][0] for n in non_wall_robust])
        robust_hi_local = np.array([local_aabbs[n][1] for n in non_wall_robust])
        scene_min_local = robust_lo_local.min(axis=0)
        scene_max_local = robust_hi_local.max(axis=0)

        Z_DOMINANT_THRESH = 0.5
        if anchor_name is not None:
            anchors_for_back = [anchor_name]
            alo, ahi = local_aabbs[anchor_name]
            n_z_component = float(n_xz[1])
            if n_z_component > Z_DOMINANT_THRESH:
                at_max_side = True
            else:
                gap_to_max = scene_max_local[2]-ahi[2]
                gap_to_min = alo[2]-scene_min_local[2]
                at_max_side = gap_to_max <= gap_to_min
        else:
            anchors_for_back = [n for n in major_voters if n in local_aabbs]
            n_z_component = float(n_xz[1])
            if n_z_component > Z_DOMINANT_THRESH:
                at_max_side = True
            else:
                w_max = 0.0; w_min = 0.0
                for n in anchors_for_back:
                    lo, hi = local_aabbs[n]
                    area = max(1e-6,(hi[0]-lo[0])*(hi[2]-lo[2]))
                    gmax = max(1e-6, scene_max_local[2]-hi[2])
                    gmin = max(1e-6, lo[2]-scene_min_local[2])
                    w_max += area/gmax; w_min += area/gmin
                at_max_side = w_max >= w_min

        _floor_rooted = [n for n in non_wall_robust if parent_of.get(n) in ("floor","floor-wall")]
        if not _floor_rooted: _floor_rooted = list(non_wall_robust)

        if at_max_side:
            back_face_local  = max(local_aabbs[n][1][2] for n in _floor_rooted)
        else:
            back_face_local  = min(local_aabbs[n][0][2] for n in _floor_rooted)
        back_wall_pos_local = back_face_local+WALL_MARGIN if at_max_side else back_face_local-WALL_MARGIN

        side_min_local = min(local_aabbs[n][0][0] for n in non_wall_robust) - SIDE_WALL_MARGIN
        side_max_local = max(local_aabbs[n][1][0] for n in non_wall_robust) + SIDE_WALL_MARGIN

        _all_local_v    = [local_aabbs[n][0][2] for n in robust_names if n in local_aabbs]
        _all_local_v_hi = [local_aabbs[n][1][2] for n in robust_names if n in local_aabbs]
        if at_max_side:
            front_v_local = (min(_all_local_v) if _all_local_v else scene_min_local[2]) - SIDE_WALL_MARGIN
        else:
            front_v_local = (max(_all_local_v_hi) if _all_local_v_hi else scene_max_local[2]) + SIDE_WALL_MARGIN

        print(f"[Wall/oriented] back_wall v={back_wall_pos_local:.4f}  "
              f"side_u_min={side_min_local:.4f}  side_u_max={side_max_local:.4f}")
        oriented_mode = True
    else:
        normal_axis, at_max_side, back_wall_pos = determine_primary_wall(
            floor_wall_names, wall_names, aabbs, scene_min, scene_max)
        perp_axis  = 2 if normal_axis == 0 else 0
        axis_label = {0:"X", 2:"Z"}
        print(f"[Wall] back-wall normal={axis_label[normal_axis]}  "
              f"pos={back_wall_pos:.4f}  at_max={at_max_side}")
        side_min_pos, side_max_pos = compute_perp_wall_positions(
            floor_wall_names, wall_names, aabbs, perp_axis, scene_min, scene_max)
        side_min_pos = min(side_min_pos, scene_min[perp_axis]-WALL_MARGIN)
        side_max_pos = max(side_max_pos, scene_max[perp_axis]+WALL_MARGIN)
        oriented_mode = False

    # 4. Assign wall objects and compute poses
    valid_wall = [n for n in wall_names if n in aabbs]
    if not oriented_mode:
        wall_assign = assign_wall_objects_to_walls(
            valid_wall, aabbs, normal_axis, at_max_side,
            back_wall_pos, side_min_pos, side_max_pos)
    else:
        wall_assign = assign_wall_objects_to_walls(
            valid_wall, local_aabbs, 2, at_max_side,
            back_wall_pos_local, side_min_local, side_max_local,
            front_wall_pos=front_v_local)

    has_side_min = any(a=="side_min" for a in wall_assign.values())
    has_side_max = any(a=="side_max" for a in wall_assign.values())
    has_front    = any(a=="front"    for a in wall_assign.values())
    if force_three_walls:
        gen_side_min = gen_side_max = True
    else:
        gen_side_max = has_side_max
        gen_side_min = has_side_min or (not has_side_max and not has_front)
    gen_front = has_front

    new_poses = dict(poses_dict)

    def wall_plane_world(assignment: str):
        if not oriented_mode:
            ex = np.array([1.0,0.0],dtype=np.float64); ez = np.array([0.0,1.0],dtype=np.float64)
            if assignment == "back":
                if normal_axis == 2:
                    return np.array([0.0,back_wall_pos],dtype=np.float64), (-ez if at_max_side else ez), ex
                else:
                    return np.array([back_wall_pos,0.0],dtype=np.float64), (-ex if at_max_side else ex), ez
            elif assignment == "side_min":
                if perp_axis == 0:
                    return np.array([side_min_pos,0.0],dtype=np.float64), ex, ez
                else:
                    return np.array([0.0,side_min_pos],dtype=np.float64), ez, ex
            else:
                if perp_axis == 0:
                    return np.array([side_max_pos,0.0],dtype=np.float64), -ex, ez
                else:
                    return np.array([0.0,side_max_pos],dtype=np.float64), -ez, ex
        else:
            def _w(u,v):
                xz=u*u_xz+v*n_xz; return np.array([xz[0],xz[1]],dtype=np.float64)
            if assignment == "back":
                p=_w(0.0,back_wall_pos_local); inward=(-n_xz if at_max_side else n_xz); tangent=u_xz
            elif assignment == "side_min":
                p=_w(side_min_local,0.0); inward=u_xz; tangent=n_xz
            elif assignment == "front":
                p=_w(0.0,front_v_local); inward=(n_xz if at_max_side else -n_xz); tangent=u_xz
            else:
                p=_w(side_max_local,0.0); inward=-u_xz; tangent=n_xz
            inward  = inward  / max(1e-12, np.linalg.norm(inward))
            tangent = tangent / max(1e-12, np.linalg.norm(tangent))
            return p, inward, tangent

    def _aabb_intersects(a_lo, a_hi, b_lo, b_hi, margin=0.0):
        return (a_lo[0]<=b_hi[0]-margin and a_hi[0]>=b_lo[0]+margin and
                a_lo[1]<=b_hi[1]-margin and a_hi[1]>=b_lo[1]+margin and
                a_lo[2]<=b_hi[2]-margin and a_hi[2]>=b_lo[2]+margin)

    def _aabb_overlap_volume(a_lo, a_hi, b_lo, b_hi, margin=0.0):
        overlap = np.minimum(a_hi, b_hi-margin) - np.maximum(a_lo, b_lo+margin)
        return 0.0 if np.any(overlap<=0.0) else float(np.prod(overlap))

    def _push_group_to_wall(group_names, plane_p, plane_inward, tgt_d, blocker_names,
                            obj_margin=0.002, max_move=0.30, binary_steps=24):
        """Find optimal translation s along plane_inward so group back-face reaches tgt_d
        without introducing new collisions with blockers.
        s < 0: push toward wall; s > 0: retreat from wall."""
        def _aabb_at(name, s):
            p = np.array(new_poses[name]["pos"],dtype=np.float64)
            p[0] += s*float(plane_inward[0]); p[2] += s*float(plane_inward[1])
            q = np.array(new_poses[name]["rot"],dtype=np.float64)
            vw = transform_cloud_from_pose(mesh_local_verts[name], p, q)
            return vw.min(axis=0), vw.max(axis=0)

        valid_bl = [bn for bn in blocker_names if bn in mesh_local_verts and bn not in group_names]

        def _dmin(s):
            vals = []
            for gn in group_names:
                if gn not in mesh_local_verts: continue
                p = np.array(new_poses[gn]["pos"],dtype=np.float64)
                p[0] += s*float(plane_inward[0]); p[2] += s*float(plane_inward[1])
                q = np.array(new_poses[gn]["rot"],dtype=np.float64)
                vw = transform_cloud_from_pose(mesh_local_verts[gn], p, q)
                vals.append(float(_wall_depth_ref_xz(vw[:,[0,2]], plane_p, plane_inward, "min")))
            return min(vals) if vals else tgt_d

        if not valid_bl:
            return float(np.clip(tgt_d-_dmin(0.0), -max_move, max_move))

        blocker_aabbs   = {bn: _aabb_at(bn, 0.0) for bn in valid_bl}
        baseline_hits   = set()
        baseline_overlap = {}
        for gn in group_names:
            if gn not in mesh_local_verts: continue
            ga0 = _aabb_at(gn, 0.0)
            for bn in valid_bl:
                blo,bhi = blocker_aabbs[bn]
                if _aabb_intersects(ga0[0],ga0[1],blo,bhi,margin=obj_margin):
                    baseline_hits.add((gn,bn))
                    baseline_overlap[(gn,bn)] = _aabb_overlap_volume(ga0[0],ga0[1],blo,bhi,margin=obj_margin)

        def _no_new_collision(s):
            for gn in group_names:
                if gn not in mesh_local_verts: continue
                ga = _aabb_at(gn, s)
                for bn in valid_bl:
                    blo,bhi = blocker_aabbs[bn]
                    if _aabb_intersects(ga[0],ga[1],blo,bhi,margin=obj_margin):
                        if (gn,bn) in baseline_hits:
                            cur_ov = _aabb_overlap_volume(ga[0],ga[1],blo,bhi,margin=obj_margin)
                            if cur_ov <= baseline_overlap.get((gn,bn),0.0)+1e-9: continue
                        return False
            return True

        cur_dmin = _dmin(0.0)
        s_target = float(np.clip(tgt_d-cur_dmin, -max_move, max_move))

        if s_target < -1e-4:
            def _feasible(s): return _dmin(s) >= tgt_d-1e-9 and _no_new_collision(s)
            best_s = 0.0
            for a in np.linspace(0.0,1.0,41):
                s_try = a*s_target
                if _feasible(s_try): best_s = s_try
                else: break
            lo, hi = s_target, best_s
            for _ in range(binary_steps):
                mid = 0.5*(lo+hi)
                if _feasible(mid): hi=mid
                else: lo=mid
            return hi

        if s_target > 1e-4:
            return s_target

        if _no_new_collision(0.0): return 0.0
        best_s = max_move
        for a in np.linspace(0.0,1.0,41):
            s_try = a*max_move
            if _no_new_collision(s_try): best_s=s_try; break
        lo, hi = 0.0, best_s
        for _ in range(binary_steps):
            mid = 0.5*(lo+hi)
            if _no_new_collision(mid): hi=mid
            else: lo=mid
        return hi

    def apply_plane_margin_to_pose(local_verts, pos, rot, plane_p, plane_inward,
                                   target_back_d, depth_policy="min"):
        vw    = transform_cloud_from_pose(local_verts, pos, rot)
        d_ref = _wall_depth_ref_xz(vw[:,[0,2]], plane_p, plane_inward, depth_policy)
        delta = (target_back_d-d_ref) * plane_inward
        pos2  = np.array(pos, dtype=np.float64).copy()
        pos2[0] += float(delta[0]); pos2[2] += float(delta[1])
        return pos2, d_ref

    wall_object_poses = {}
    for name in valid_wall:
        assignment = wall_assign.get(name, "back")
        orig_pos = np.array(poses_dict[name]["pos"],dtype=np.float64) if name in poses_dict \
                   else np.array([0.0,base_dy,0.0],dtype=np.float64)
        orig_rot = np.array(poses_dict[name]["rot"],dtype=np.float64) if name in poses_dict \
                   else np.array([0.0,0.0,0.0,1.0],dtype=np.float64)
        local_verts = mesh_local_verts.get(name)
        if local_verts is None:
            wall_object_poses[name] = {"pos":orig_pos.tolist(),"rot":orig_rot.tolist(),"lin_vel":[0.,0.,0.]}
            new_poses[name] = wall_object_poses[name]; continue

        plane_p, plane_inward, wall_tangent = wall_plane_world(assignment)
        tgt_d = WALL_OBJ_INSET; depth_pol = "hull_aabb"

        _group_child_names = [c for c in children_of.get(name,[])
                              if c in _best_child_poses_lookup and c in mesh_local_verts]

        def _group_back_face_depth(root_lv, root_pos, root_rot, plane_p, plane_inward):
            root_world = transform_cloud_from_pose(root_lv, root_pos, root_rot)
            xz_parts   = [root_world[:,[0,2]]]
            for _cn in _group_child_names:
                if _cn in _best_child_world_verts:
                    xz_parts.append(_best_child_world_verts[_cn][:,[0,2]])
                elif _cn in _best_child_poses_lookup and _cn in mesh_local_verts:
                    _cp = _best_child_poses_lookup[_cn]
                    _cw = transform_cloud_from_pose(
                        mesh_local_verts[_cn],
                        np.array(_cp["pos"],dtype=np.float64),
                        np.array(_cp.get("rot",[0.,0.,0.,1.]),dtype=np.float64))
                    xz_parts.append(_cw[:,[0,2]])
            xz_all = np.vstack(xz_parts)
            return float(_wall_depth_ref_xz(xz_all, plane_p, plane_inward, "hull_aabb"))

        # Stage A: translate along wall normal only
        if _group_child_names:
            _group_dmin  = _group_back_face_depth(local_verts, orig_pos, orig_rot, plane_p, plane_inward)
            _group_delta = (tgt_d-_group_dmin)*plane_inward
            pos_step1    = orig_pos.copy()
            pos_step1[0] += float(_group_delta[0]); pos_step1[2] += float(_group_delta[1])
            before_margin = _group_dmin
        else:
            pos_step1, before_margin = apply_plane_margin_to_pose(
                local_verts, orig_pos, orig_rot, plane_p, plane_inward, tgt_d, depth_pol)

        vw_cat = transform_cloud_from_pose(local_verts, pos_step1, orig_rot)
        d_cat  = (vw_cat[:,[0,2]]-plane_p[None,:]) @ plane_inward
        spread_catalog = float(np.percentile(d_cat,90)-np.percentile(d_cat,10))
        skip_yaw = (wall_align_max_yaw_deg <= 0.0 or _skip_wall_yaw_align(name, spread_catalog))

        if skip_yaw:
            dtheta = 0.0
            pos_aligned = np.array(pos_step1,dtype=np.float64).copy()
            rot_step2   = np.array(orig_rot,dtype=np.float64).copy()
            p10 = float(np.percentile(d_cat,10)); p90 = float(np.percentile(d_cat,90))
        else:
            # Stage B: yaw search for minimum depth spread
            MAX_ALIGN_DEG = float(wall_align_max_yaw_deg)
            coarse = np.linspace(-np.deg2rad(MAX_ALIGN_DEG), np.deg2rad(MAX_ALIGN_DEG), 61)
            base_world  = transform_cloud_from_pose(local_verts, pos_step1, orig_rot)
            base_center = base_world.mean(axis=0)
            best = None
            for da in coarse:
                qy = quat_from_yaw(float(da)); rot_try = quat_mul(qy, orig_rot)
                rot_try = rot_try / max(1e-12, np.linalg.norm(rot_try))
                world_try = transform_cloud_from_pose(local_verts, pos_step1, rot_try)
                ctr_try   = world_try.mean(axis=0)
                pos_ctr   = np.array(pos_step1,dtype=np.float64).copy()
                pos_ctr[0] += float(base_center[0]-ctr_try[0]); pos_ctr[2] += float(base_center[2]-ctr_try[2])
                pos_try, _ = apply_plane_margin_to_pose(local_verts, pos_ctr, rot_try, plane_p, plane_inward,
                                                        WALL_OBJ_INSET, depth_pol)
                vw = transform_cloud_from_pose(local_verts, pos_try, rot_try)
                d  = (vw[:,[0,2]]-plane_p[None,:]) @ plane_inward
                spread = float(np.percentile(d,90)-np.percentile(d,10))
                if best is None or spread < best[0]:
                    best = (spread, da, pos_try, rot_try, float(np.percentile(d,10)), float(np.percentile(d,90)))
            _, dtheta, pos_aligned, rot_step2, p10, p90 = best

        # Forbid tangential drift
        c0 = transform_cloud_from_pose(local_verts, orig_pos, orig_rot).mean(axis=0)
        c1 = transform_cloud_from_pose(local_verts, pos_aligned, rot_step2).mean(axis=0)
        tangential_drift = float((c1[[0,2]]-c0[[0,2]]) @ wall_tangent)
        if abs(tangential_drift) > 1e-6:
            pos_aligned = np.array(pos_aligned, dtype=np.float64)
            pos_aligned[0] -= tangential_drift*wall_tangent[0]
            pos_aligned[2] -= tangential_drift*wall_tangent[1]
            pos_aligned, _ = apply_plane_margin_to_pose(local_verts, pos_aligned, rot_step2,
                                                        plane_p, plane_inward, tgt_d, depth_pol)

        new_poses[name] = {"pos":pos_aligned.tolist(),"rot":rot_step2.tolist(),"lin_vel":[0.,0.,0.]}
        _bl_names = [n for n in floor_wall_names if n in mesh_local_verts]
        _s_bl     = _push_group_to_wall([name], plane_p, plane_inward, tgt_d, _bl_names)
        if abs(_s_bl) > 1e-4:
            pos_aligned[0] += _s_bl*float(plane_inward[0])
            pos_aligned[2] += _s_bl*float(plane_inward[1])
            new_poses[name]["pos"] = pos_aligned.tolist()

        print(f"  [Place/wall] {name} -> {assignment}  d_ref={before_margin:.4f}  "
              f"yaw={'skip' if skip_yaw else f'{np.degrees(dtheta):+.2f}deg'}  "
              f"spread={spread_catalog:.4f}")
        wall_object_poses[name] = new_poses[name]

    # Ceiling objects: align top to room_height
    for name in ceiling_names:
        if name not in new_poses:
            local_verts = mesh_local_verts.get(name)
            pos_y = (float(y_range[1]) - float(local_verts[:,1].max())) if local_verts is not None else base_dy
            new_poses[name] = {"pos":[0.0,pos_y,0.0],"rot":[0.,0.,0.,1.],"lin_vel":[0.,0.,0.]}
            print(f"  [Ceiling] {name} -> pos_y={pos_y:.4f}")

    moved_floor_wall_objects: set = set()

    def collect_descendants(root_name):
        out, stack, seen = [], [root_name], set()
        while stack:
            cur = stack.pop()
            if cur in seen: continue
            seen.add(cur); out.append(cur)
            for ch in children_of.get(cur,[]): stack.append(ch)
        return out

    # 6c. Anti-penetration: push wall objects outward to clear floor furniture
    ANTI_PEN_CLEARANCE = 0.02
    _wall_ceil_roots = set(wall_names+ceiling_names)

    def _has_wall_ancestor(name):
        cur = parent_of.get(name)
        while cur:
            if cur in _wall_ceil_roots: return True
            cur = parent_of.get(cur)
        return False

    ref_names_pen = [n for n in movable_names if n in aabbs and not _has_wall_ancestor(n)
                     and parent_of.get(n) in ("floor","floor-wall")]
    if not ref_names_pen:
        ref_names_pen = [n for n in movable_names if n in aabbs and not _has_wall_ancestor(n)]

    _wall_labels_for_antpen = ["back","side_min","side_max"]
    if oriented_mode and front_v_local is not None and any(a=="front" for a in wall_assign.values()):
        _wall_labels_for_antpen.append("front")

    for wall_lbl in _wall_labels_for_antpen:
        assigned_pen = [n for n,a in wall_assign.items() if a==wall_lbl
                        and n in wall_object_poses and mesh_local_verts.get(n) is not None]
        if not assigned_pen: continue

        plane_p, plane_inward, wall_tangent = wall_plane_world(wall_lbl)
        outward = -plane_inward

        max_front_d = -np.inf; tan_lo = np.inf; tan_hi = -np.inf
        for name in assigned_pen:
            pose = wall_object_poses[name]
            vw   = transform_cloud_from_pose(mesh_local_verts[name], pose["pos"], pose["rot"])
            xz   = vw[:,[0,2]]
            d_in  = (xz-plane_p[None,:]) @ plane_inward
            d_tan = (xz-plane_p[None,:]) @ wall_tangent
            max_front_d = max(max_front_d, float(d_in.max()))
            tan_lo = min(tan_lo, float(d_tan.min()))
            tan_hi = max(tan_hi, float(d_tan.max()))

        min_ref_inward = np.inf
        for name in ref_names_pen:
            lo, hi = aabbs[name]
            corners = np.array([[lo[0],lo[2]],[lo[0],hi[2]],[hi[0],lo[2]],[hi[0],hi[2]]],dtype=np.float64)
            d_tan = (corners-plane_p[None,:]) @ wall_tangent
            if d_tan.max() < tan_lo-0.05 or d_tan.min() > tan_hi+0.05: continue
            d_in = (corners-plane_p[None,:]) @ plane_inward
            if float(d_in.max()) > 0:
                d_min_aabb = float(d_in.min())
                d_min_val  = d_min_aabb
                if d_min_aabb < 0.0 and name in clouds:
                    _d_full  = (clouds[name][:,[0,2]]-plane_p[None,:]) @ plane_inward
                    d_min_val = float(_d_full.min())
                min_ref_inward = min(min_ref_inward, max(0.0, d_min_val))

        if np.isinf(min_ref_inward): continue
        penetration = max_front_d - min_ref_inward + ANTI_PEN_CLEARANCE
        if wall_lbl == "back" and penetration > ANTI_PEN_BACK_MAX_SHIFT:
            penetration = ANTI_PEN_BACK_MAX_SHIFT
        if penetration <= 0.0: continue

        print(f"  [AntiPen/{wall_lbl}] shift={penetration:.4f}m")
        for name in assigned_pen:
            pos = np.array(wall_object_poses[name]["pos"],dtype=np.float64)
            pos[0] += outward[0]*penetration; pos[2] += outward[1]*penetration
            wall_object_poses[name]["pos"] = pos.tolist()
            new_poses[name] = wall_object_poses[name]

        if oriented_mode:
            if   wall_lbl=="side_min": side_min_local -= penetration
            elif wall_lbl=="side_max": side_max_local += penetration
            elif wall_lbl=="front":    front_v_local += penetration if not at_max_side else -penetration
            else:                      back_wall_pos_local += penetration if at_max_side else -penetration
        else:
            if   wall_lbl=="side_min": side_min_pos -= penetration
            elif wall_lbl=="side_max": side_max_pos += penetration
            else:                      back_wall_pos += penetration if at_max_side else -penetration

    # 6d. Push floor-wall objects toward nearest wall
    FW_GROUP_MARGIN = 0.02; FW_OBJ_MARGIN = 0.002; FW_MAX_MOVE = 0.30; FW_BINARY_STEPS = 24

    for _bcn, _bcp in _best_child_poses_lookup.items():
        if _bcn not in new_poses:
            new_poses[_bcn] = {"pos":list(_bcp["pos"]),"rot":list(_bcp.get("rot",[0.,0.,0.,1.])),"lin_vel":[0.,0.,0.]}

    fw_processed: set = set()
    for fw_root in floor_wall_names:
        if fw_root in fw_processed: continue
        group = [n for n in collect_descendants(fw_root) if n in new_poses and n in mesh_local_verts]
        if not group: fw_processed.add(fw_root); continue
        fw_processed.update(group)

        def _obj_world_fw(name):
            p=np.array(new_poses[name]["pos"],dtype=np.float64); q=np.array(new_poses[name]["rot"],dtype=np.float64)
            return transform_cloud_from_pose(mesh_local_verts[name], p, q)

        group_verts_all   = np.vstack([_obj_world_fw(gn) for gn in group])
        face_normal_xz    = estimate_normal_from_cloud_xz(group_verts_all)

        _fw_wall_lbls = ["back","side_min","side_max"]
        if oriented_mode and front_v_local is not None and any(a=="front" for a in wall_assign.values()):
            _fw_wall_lbls.append("front")
        plane_specs = {lbl: wall_plane_world(lbl) for lbl in _fw_wall_lbls}

        group_dmin     = {}; wall_alignment = {}
        for lbl, (pp,pin,pt) in plane_specs.items():
            rr = []
            for gn in group:
                vw = _obj_world_fw(gn); xz = vw[:,[0,2]]; d=(xz-pp[None,:])@pin; rr.append(float(d.min()))
            group_dmin[lbl]     = min(rr)
            wall_alignment[lbl] = abs(float(np.dot(face_normal_xz, pin)))

        best_lbl = max(wall_alignment, key=lambda k: (round(wall_alignment[k],2), -group_dmin[k]))
        best_p, best_in, best_t = plane_specs[best_lbl]
        cur_dmin = group_dmin[best_lbl]

        blocker_names_fw = [n for n in (valid_wall+floor_wall_names)
                            if n not in group and n in mesh_local_verts]
        s = _push_group_to_wall(group, best_p, best_in, FW_GROUP_MARGIN,
                                blocker_names_fw, FW_OBJ_MARGIN, FW_MAX_MOVE, FW_BINARY_STEPS)
        s = float(np.clip(s, -FW_MAX_MOVE, FW_MAX_MOVE))
        if abs(s) < 1e-4:
            print(f"  [FWPush] {fw_root}: no move (dmin={cur_dmin:.4f})"); continue
        delta = s*best_in
        for gn in group:
            new_poses[gn]["pos"][0] = float(new_poses[gn]["pos"][0]+delta[0])
            new_poses[gn]["pos"][2] = float(new_poses[gn]["pos"][2]+delta[1])
            moved_floor_wall_objects.add(gn)
        print(f"  [FWPush] root={fw_root} wall={best_lbl} s={s:+.4f}")

    # 6b. Set poses for extra-fixed objects
    _zero_pos = [0.0,0.0,0.0]; _id_rot = [0.0,0.0,0.0,1.0]
    for _n in _extra_fixed:
        _par = parent_of.get(_n)
        if _par and _par in new_poses:
            _par_start = poses_dict.get(_par, {"pos":_zero_pos,"rot":_id_rot})
            _par_final = new_poses[_par]
            _dx = float(_par_final["pos"][0])-float(_par_start["pos"][0])
            _dz = float(_par_final["pos"][2])-float(_par_start["pos"][2])
            if _n in _best_child_poses_lookup:
                _p1 = _best_child_poses_lookup[_n]
                _p1_pos = _p1["pos"]; _p1_rot = _p1.get("rot",_id_rot)
                _final_pos = [float(_p1_pos[0])+_dx, float(_p1_pos[1]), float(_p1_pos[2])+_dz]
                new_poses[_n] = {"pos":_final_pos,"rot":list(_p1_rot),"lin_vel":[0.,0.,0.]}
                print(f"[Extra fixed/wall-child] {_n}: delta=({_dx:+.4f},{_dz:+.4f})")
            else:
                new_poses[_n] = {"pos":[_dx,0.0,_dz],"rot":_id_rot,"lin_vel":[0.,0.,0.]}
                print(f"[Extra fixed] {_n}: parent '{_par}' delta=({_dx:+.4f},{_dz:+.4f})")
        else:
            new_poses[_n] = {"pos":list(_zero_pos),"rot":_id_rot,"lin_vel":[0.,0.,0.]}

    # 6e. Propagate wall root fitting delta to descendants already in poses_dict
    for _wall_root in valid_wall:
        if _wall_root not in new_poses or _wall_root not in poses_dict: continue
        _r_start = poses_dict[_wall_root]["pos"]; _r_final = new_poses[_wall_root]["pos"]
        _rdx = float(_r_final[0])-float(_r_start[0]); _rdz = float(_r_final[2])-float(_r_start[2])
        _rot_start_np = np.array(poses_dict[_wall_root].get("rot",[0.,0.,0.,1.]),dtype=np.float64)
        _rot_final_np = np.array(new_poses[_wall_root].get("rot",[0.,0.,0.,1.]),dtype=np.float64)
        _has_rot_delta = bool(np.any(np.abs(_rot_final_np-_rot_start_np) > 1e-6))
        for _wc in collect_descendants(_wall_root):
            if _wc == _wall_root: continue
            if _wc in poses_dict and _wc not in valid_wall and _wc not in _extra_fixed:
                _wcp = poses_dict[_wc]["pos"]; _wcr = poses_dict[_wc].get("rot",[0.,0.,0.,1.])
                _new_rot = quat_mul(_rot_final_np, np.array(_wcr,dtype=np.float64)).tolist() \
                           if _has_rot_delta else list(_wcr)
                new_poses[_wc] = {
                    "pos":[float(_wcp[0])+_rdx, float(_wcp[1]), float(_wcp[2])+_rdz],
                    "rot":_new_rot, "lin_vel":[0.,0.,0.]}

    # 6f. Sync wall object poses
    for _wn in wall_object_poses:
        new_poses[_wn] = wall_object_poses[_wn]

    # 5. Save JSON (optional)
    if not oriented_mode:
        out_walls = {
            "mode": "axis_aligned",
            "back":     {"normal_axis": axis_label[normal_axis], "position": float(back_wall_pos)},
            "side_min": {"normal_axis": axis_label[perp_axis],   "position": float(side_min_pos)},
            "side_max": {"normal_axis": axis_label[perp_axis],   "position": float(side_max_pos)},
        }
    else:
        _ow = {
            "mode": "oriented",
            "frame": {"tangent_u_xz":[float(u_xz[0]),float(u_xz[1])],
                      "normal_n_xz": [float(n_xz[0]),float(n_xz[1])]},
            "back":     {"v_position": float(back_wall_pos_local), "at_max_side": bool(at_max_side)},
            "side_min": {"u_position": float(side_min_local)},
            "side_max": {"u_position": float(side_max_local)},
        }
        if gen_front and front_v_local is not None:
            _ow["front"] = {"v_position": float(front_v_local)}
        out_walls = _ow

    _wall_obj_dir  = wall_obj_dir  if wall_obj_dir  is not None else \
        os.path.join(os.path.dirname(os.path.abspath(output_dir)), "objs_walls")
    _wall_urdf_dir = wall_urdf_dir if wall_urdf_dir is not None else _wall_obj_dir
    os.makedirs(_wall_obj_dir,  exist_ok=True)
    os.makedirs(_wall_urdf_dir, exist_ok=True)
    os.makedirs(output_dir, exist_ok=True)
    def _yaw_quat_from_tangent(tx, tz):
        return quat_from_yaw(float(np.arctan2(tz, tx))).tolist()

    if not oriented_mode:
        if normal_axis == 2:
            back_center   = [0.5*(side_min_pos+side_max_pos), 0.5*y_range[1], back_wall_pos]
            side_min_center = [side_min_pos, 0.5*y_range[1], 0.5*((scene_min[normal_axis]-SIDE_WALL_MARGIN)+back_wall_pos)]
            side_max_center = [side_max_pos, 0.5*y_range[1], 0.5*((scene_min[normal_axis]-SIDE_WALL_MARGIN)+back_wall_pos)]
            q_back = quat_from_yaw(0.0).tolist(); q_side = quat_from_yaw(np.pi*0.5).tolist()
        else:
            back_center   = [back_wall_pos, 0.5*y_range[1], 0.5*(side_min_pos+side_max_pos)]
            side_min_center = [0.5*((scene_min[normal_axis]-SIDE_WALL_MARGIN)+back_wall_pos), 0.5*y_range[1], side_min_pos]
            side_max_center = [0.5*((scene_min[normal_axis]-SIDE_WALL_MARGIN)+back_wall_pos), 0.5*y_range[1], side_max_pos]
            q_back = quat_from_yaw(np.pi*0.5).tolist(); q_side = quat_from_yaw(0.0).tolist()
    else:
        def local_to_world_xz(u, v):
            xz = u*u_xz+v*n_xz; return float(xz[0]), float(xz[1])
        bx0,bz0 = local_to_world_xz(side_min_local, back_wall_pos_local)
        bx1,bz1 = local_to_world_xz(side_max_local, back_wall_pos_local)
        back_center = [0.5*(bx0+bx1), 0.5*y_range[1], 0.5*(bz0+bz1)]
        sx0,sz0 = local_to_world_xz(side_min_local, front_v_local)
        sx1,sz1 = local_to_world_xz(side_min_local, back_wall_pos_local)
        side_min_center = [0.5*(sx0+sx1), 0.5*y_range[1], 0.5*(sz0+sz1)]
        tx0,tz0 = local_to_world_xz(side_max_local, front_v_local)
        tx1,tz1 = local_to_world_xz(side_max_local, back_wall_pos_local)
        side_max_center = [0.5*(tx0+tx1), 0.5*y_range[1], 0.5*(tz0+tz1)]
        if gen_front and front_v_local is not None:
            fx0,fz0 = local_to_world_xz(side_min_local, front_v_local)
            fx1,fz1 = local_to_world_xz(side_max_local, front_v_local)
            front_center = [0.5*(fx0+fx1), 0.5*y_range[1], 0.5*(fz0+fz1)]
        q_back = _yaw_quat_from_tangent(u_xz[0], u_xz[1])
        q_side = _yaw_quat_from_tangent(n_xz[0], n_xz[1])

    walls_pose_out = {"back": {"pos":back_center,"rot":q_back}}
    if gen_side_min: walls_pose_out["side_min"]      = {"pos":side_min_center,"rot":q_side}
    if gen_side_max: walls_pose_out["side_wall_max"] = {"pos":side_max_center,"rot":q_side}
    if gen_front and oriented_mode and front_v_local is not None:
        walls_pose_out["front"] = {"pos":front_center,"rot":q_back}

    # Add wall geometry as fixed actors with identity pose.
    # Wall OBJs are world-frame (mesh vertices at actual wall positions), so physics
    # places them correctly with fix_base_link=True at (0,0,0).
    _id_wall_pose = {"pos": [0.0, 0.0, 0.0], "rot": [0.0, 0.0, 0.0, 1.0], "lin_vel": [0.0, 0.0, 0.0]}
    new_poses["wall_back"] = _id_wall_pose.copy()
    if gen_side_min: new_poses["wall_side_min"] = _id_wall_pose.copy()
    if gen_side_max: new_poses["wall_side_max"] = _id_wall_pose.copy()
    if gen_front and oriented_mode and front_v_local is not None:
        new_poses["wall_front"] = _id_wall_pose.copy()

    replay_data = {"base_dy":base_dy,"objects":new_poses,"walls_pose":walls_pose_out,"walls":out_walls}
    if out_json_name is not None:
        replay_out_json = os.path.join(output_dir, out_json_name)
        with open(replay_out_json,"w") as f:
            json.dump(replay_data, f, indent=2)
        print(f"[Save] Replay JSON -> {replay_out_json}  ({len(new_poses)} objects)")

    # 6. Export wall mesh OBJs
    back_wall_obj  = os.path.join(_wall_obj_dir, "wall_back.obj")
    side_min_obj   = os.path.join(_wall_obj_dir, "wall_side_min.obj")
    side_max_obj   = os.path.join(_wall_obj_dir, "wall_side_max.obj")
    front_wall_obj = os.path.join(_wall_obj_dir, "wall_front.obj")

    for _stale in [side_min_obj, side_max_obj, front_wall_obj]:
        if os.path.isfile(_stale): os.remove(_stale)

    if not oriented_mode:
        parallel_range = (side_min_pos, side_max_pos)
        side_para_range = (scene_min[normal_axis]-SIDE_WALL_MARGIN, back_wall_pos)
        bw_sign = 1 if at_max_side else -1
        make_wall_obj(*parallel_range, normal_axis, back_wall_pos, y_range, back_wall_obj, bw_sign)
        if gen_side_min: make_wall_obj(*side_para_range, perp_axis, side_min_pos, y_range, side_min_obj, -1)
        if gen_side_max: make_wall_obj(*side_para_range, perp_axis, side_max_pos, y_range, side_max_obj,  1)
    else:
        def local_to_world_xz(u, v):
            xz=u*u_xz+v*n_xz; return float(xz[0]),float(xz[1])
        p0=local_to_world_xz(side_min_local,back_wall_pos_local)
        p1=local_to_world_xz(side_max_local,back_wall_pos_local)
        back_out = n_xz if at_max_side else -n_xz
        make_wall_obj_oriented(p0, p1, back_out, y_range, back_wall_obj)
        if gen_side_min:
            s0=local_to_world_xz(side_min_local,front_v_local); s1=local_to_world_xz(side_min_local,back_wall_pos_local)
            make_wall_obj_oriented(s0, s1, -u_xz, y_range, side_min_obj)
        if gen_side_max:
            t0=local_to_world_xz(side_max_local,front_v_local); t1=local_to_world_xz(side_max_local,back_wall_pos_local)
            make_wall_obj_oriented(t0, t1, u_xz, y_range, side_max_obj)
        if gen_front and front_v_local is not None:
            f0=local_to_world_xz(side_min_local,front_v_local); f1=local_to_world_xz(side_max_local,front_v_local)
            front_out = n_xz if (not at_max_side) else -n_xz
            make_wall_obj_oriented(f0, f1, front_out, y_range, front_wall_obj)

    print(f"[Export] back wall OBJ -> {back_wall_obj}")

    # 8b. Generate URDF stubs for wall meshes
    def _write_wall_urdf(obj_fname, urdf_path):
        rname = os.path.splitext(os.path.basename(urdf_path))[0]
        urdf_str = (
            '<?xml version="1.0"?>\n'
            f'<robot name="{rname}">\n'
            '  <link name="base">\n'
            '    <visual><geometry>'
            f'<mesh filename="{obj_fname}" scale="1 1 1"/>'
            '</geometry></visual>\n'
            '    <collision><geometry>'
            f'<mesh filename="{obj_fname}" scale="1 1 1"/>'
            '</geometry></collision>\n'
            '    <inertial><mass value="1.0"/>'
            '<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>'
            '</inertial>\n'
            '  </link>\n</robot>\n'
        )
        with open(urdf_path,"w") as _uf: _uf.write(urdf_str)

    def _wall_obj_ref(obj_name):
        """Relative path from URDF dir to OBJ file (handles urdf_dir != obj_dir)."""
        if os.path.normpath(_wall_urdf_dir) == os.path.normpath(_wall_obj_dir):
            return obj_name
        return os.path.relpath(os.path.join(_wall_obj_dir, obj_name), _wall_urdf_dir)

    _write_wall_urdf(_wall_obj_ref("wall_back.obj"),     os.path.join(_wall_urdf_dir,"wall_back.urdf"))
    if gen_side_min: _write_wall_urdf(_wall_obj_ref("wall_side_min.obj"), os.path.join(_wall_urdf_dir,"wall_side_min.urdf"))
    if gen_side_max: _write_wall_urdf(_wall_obj_ref("wall_side_max.obj"), os.path.join(_wall_urdf_dir,"wall_side_max.urdf"))
    if gen_front:    _write_wall_urdf(_wall_obj_ref("wall_front.obj"),    os.path.join(_wall_urdf_dir,"wall_front.urdf"))

    # 7. Debug OBJ exports (optional)
    if debug_save_obj:
        for name, pose in wall_object_poses.items():
            src = os.path.join(obj_dir, f"{prefix}{name}.obj")
            if not os.path.isfile(src): continue
            export_transformed_obj(src, pose["pos"], pose["rot"],
                                   os.path.join(output_dir, f"phase2_wall_placed_{name}.obj"))
        for name in sorted(moved_floor_wall_objects):
            if name not in new_poses: continue
            src = os.path.join(obj_dir, f"{prefix}{name}.obj")
            if not os.path.isfile(src): continue
            export_transformed_obj(src, new_poses[name]["pos"], new_poses[name]["rot"],
                                   os.path.join(output_dir, f"phase2_wall_moved_{name}.obj"))

    # 10. Export objs_walls/ folder
    print(f"[objs_walls] Exporting to: {_wall_obj_dir}")
    _id_pos = [0.0,base_dy,0.0]; _id_rot_e = [0.0,0.0,0.0,1.0]
    _ow_exported = 0
    for name in all_names:
        if name in _best_child_obj_paths and os.path.isfile(_best_child_obj_paths[name]):
            _par_name = parent_of.get(name)
            _par_pose = new_poses.get(_par_name) if _par_name else None
            if _par_pose is not None:
                _export_pos = _par_pose["pos"]; _export_rot = _par_pose.get("rot",_id_rot_e)
            else:
                _p1_pos = (_best_child_poses_lookup.get(name) or poses_dict.get(name,{})).get("pos",[0.,0.,0.])
                _final  = new_poses.get(name,{}).get("pos",[0.,0.,0.])
                _export_pos = [float(_final[0])-float(_p1_pos[0]),0.0,float(_final[2])-float(_p1_pos[2])]
                _export_rot = _id_rot_e
            export_transformed_obj(_best_child_obj_paths[name], _export_pos, _export_rot,
                                   os.path.join(_wall_obj_dir, f"{name}.obj"))
            _ow_exported += 1; continue
        src = os.path.join(obj_dir, f"{prefix}{name}.obj")
        if not os.path.isfile(src): continue
        pose = new_poses.get(name) or poses_dict.get(name, {"pos":_id_pos,"rot":_id_rot_e})
        export_transformed_obj(src, pose["pos"], pose["rot"],
                               os.path.join(_wall_obj_dir, f"{name}.obj"))
        _ow_exported += 1

    print(f"[objs_walls] Exported {_ow_exported} object OBJs")
    print(f"\n=== Done ===")
    return replay_data


# ── Standalone CLI ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Place walls and wall-attached objects (Stage 3)")
    ap.add_argument("--output_dir",  required=True, help="Directory containing phase2_final_poses.json")
    ap.add_argument("--root_dir",    required=True, help="Root dir with obj_files/ and scene_tree.json")
    ap.add_argument("--scene_tree",  default="scene_tree.json")
    ap.add_argument("--margin",      type=float, default=WALL_MARGIN)
    ap.add_argument("--out_json",    default="phase2_final_poses_w_walls.json")
    ap.add_argument("--debug_save_obj", action="store_true")
    ap.add_argument("--wall_align_max_yaw_deg", type=float, default=25.0)
    ap.add_argument("--force_three_walls", action="store_true")
    args = ap.parse_args()
    run(args.output_dir, args.root_dir, args.scene_tree, args.margin, args.out_json,
        args.debug_save_obj, args.wall_align_max_yaw_deg, args.force_three_walls)


# ── Scene assembly (moved verbatim from scripts/infer_scene3d.py) ────────────
# Shared by the sam3d backend (infer_scene3d.py) and the mix3r-direct backend
# (infer_scene3d_mix3r.py); logs through the stage2 logger so both entries
# capture assembly lines in their stage2_log files.

from collections import defaultdict, deque  # noqa: E402

from rest3d.utils.log import get_logger as _get_logger  # noqa: E402
from rest3d.utils.mesh import (  # noqa: E402
    get_y_bounds,
    read_obj_vertices,
    write_obj_with_y_offset,
)

logger = _get_logger("stage2")

def place_to_ground(output_obj_y_align_dir, output_obj_canon_dir, scene_tree_path,
                    ceiling_height_threshold=1.8):
    """
    BFS over parent/child relations in scene_tree.json to adjust per-object height:
    - children of "floor": shift so the lowest vertex sits at y = 0;
    - children of "floor-wall": same as floor children (resting on floor while attached to a wall);
    - children of "wall": apply the median y-offset from floor / floor-wall children (global shift that preserves relative height);
    - children of "ceiling": same median offset as wall children;
    - other children: place the lowest vertex on top of the (already-adjusted) parent's highest vertex;
    - the floor itself is ignored.

    Finally the ceiling height is set to max(scene max-y, ceiling_threshold).
    Returns:
        ceiling_height (float): resolved ceiling height
    """
    logger.info(f"\n{'='*60}")
    logger.info(f"Place to ground according to scene tree...")
    logger.info(f"{'='*60}\n")

    with open(scene_tree_path) as f:
        scene_tree = json.load(f)

    # Build parent_map, children_map, and relation_map
    parent_map = {}
    relation_map = {}
    children_map = defaultdict(list)
    VALID_ROOTS = {"floor", "wall", "ceiling", "floor-wall"}
    for edge in scene_tree["edges"]:
        child = edge["child"]
        parent = edge["parent"]
        # Patch: parents starting with "the_floor_" should resolve to the root "floor"
        if parent.startswith("the_floor"):
            parent = "floor"
            edge["parent"] = "floor"
        parent_map[child] = parent
        relation_map[child] = edge.get("relation", "on")
        children_map[parent].append(child)

    # Pre-read all OBJ vertex data
    obj_verts = {}  # obj_name -> (vertices, lines, min_y, max_y)
    all_nodes = set()
    for root in scene_tree["roots"]:
        all_nodes.update(children_map.get(root, []))
    # BFS to collect every node
    bfs_q = deque(all_nodes)
    while bfs_q:
        n = bfs_q.popleft()
        for c in children_map.get(n, []):
            if c not in all_nodes:
                all_nodes.add(c)
                bfs_q.append(c)

    for obj_name in all_nodes:
        if obj_name.startswith("the_floor"):
            continue
        input_path = os.path.join(output_obj_y_align_dir, f"scene_y_align_{obj_name}.obj")
        if os.path.exists(input_path):
            vertices, lines = read_obj_vertices(input_path)
            min_y, max_y = get_y_bounds(vertices)
            obj_verts[obj_name] = (vertices, lines, min_y, max_y)

    # Pass 1: handle floor children, collecting y_offset to compute the reference offset
    floor_offsets = []
    max_y_after = {}
    processed = set()

    for obj_name in children_map.get("floor", []):
        if obj_name.startswith("the_floor") or obj_name not in obj_verts:
            processed.add(obj_name)
            continue
        vertices, lines, min_y, max_y = obj_verts[obj_name]
        y_offset = -min_y
        output_path = os.path.join(output_obj_canon_dir, f"scene_canon_{obj_name}.obj")
        write_obj_with_y_offset(output_path, lines, y_offset)
        max_y_after[obj_name] = max_y + y_offset
        floor_offsets.append(y_offset)
        processed.add(obj_name)
        logger.info(f"  {obj_name}: parent=floor, y=[{min_y:.4f},{max_y:.4f}] -> [0,{max_y + y_offset:.4f}]")

    # Pass 1b: handle floor-wall children (on the floor and attached to a wall); place on the floor like floor children
    for obj_name in children_map.get("floor-wall", []):
        if obj_name.startswith("the_floor") or obj_name not in obj_verts:
            processed.add(obj_name)
            continue
        vertices, lines, min_y, max_y = obj_verts[obj_name]
        y_offset = -min_y
        output_path = os.path.join(output_obj_canon_dir, f"scene_canon_{obj_name}.obj")
        write_obj_with_y_offset(output_path, lines, y_offset)
        max_y_after[obj_name] = max_y + y_offset
        floor_offsets.append(y_offset)
        processed.add(obj_name)
        logger.info(f"  {obj_name}: parent=floor-wall, y=[{min_y:.4f},{max_y:.4f}] -> [0,{max_y + y_offset:.4f}]")

    # Compute the reference offset using only objects whose min_y is meaningfully negative (< -0.05),
    # excluding outliers whose mesh is already near y = 0 (e.g. a floor lamp already reconstructed at y ~= 0)
    significant_offsets = [o for o in floor_offsets if o > 0.05]
    ref_offset = float(np.median(significant_offsets)) if significant_offsets else (
        float(np.median(floor_offsets)) if floor_offsets else 0.0
    )
    logger.info(f"\n  Reference offset from floor/floor-wall children (median, significant only): {ref_offset:.4f}\n")

    # Pass 2: handle wall children with the reference offset (global shift, preserves relative height) and clamp above the floor
    for obj_name in children_map.get("wall", []):
        if obj_name.startswith("the_floor") or obj_name not in obj_verts:
            processed.add(obj_name)
            continue
        vertices, lines, min_y, max_y = obj_verts[obj_name]
        y_offset = ref_offset + max(0.0, -(min_y + ref_offset))  # clamp to floor
        output_path = os.path.join(output_obj_canon_dir, f"scene_canon_{obj_name}.obj")
        write_obj_with_y_offset(output_path, lines, y_offset)
        max_y_after[obj_name] = max_y + y_offset
        processed.add(obj_name)
        logger.info(f"  {obj_name}: parent=wall, y_offset={y_offset:.4f}, y=[{min_y:.4f},{max_y:.4f}] -> [{min_y + y_offset:.4f},{max_y + y_offset:.4f}]")

    # Pass 2b: mark ceiling children as handled; the actual file write is done in Pass 2c (which does ceiling-align + floor clamp)
    for obj_name in children_map.get("ceiling", []):
        processed.add(obj_name)

    # Pass 3: BFS over the remaining children (grandchildren and deeper)
    queue = deque()
    for obj_name in processed:
        for child in children_map.get(obj_name, []):
            if child not in processed:
                queue.append(child)

    while queue:
        obj_name = queue.popleft()
        if obj_name in processed:
            continue

        if obj_name.startswith("the_floor"):
            processed.add(obj_name)
            continue

        if obj_name not in obj_verts:
            logger.info(f"  Warning: {obj_name} obj not found, skipping")
            processed.add(obj_name)
            continue

        vertices, lines, min_y, max_y = obj_verts[obj_name]
        parent = parent_map.get(obj_name, "floor")
        relation = relation_map.get(obj_name, "on")
        output_path = os.path.join(output_obj_canon_dir, f"scene_canon_{obj_name}.obj")

        if parent in max_y_after:
            if relation == "inside":
                # "inside": the y-align reconstruction already positions the child correctly
                # relative to the parent (e.g. on an interior shelf). Apply the same y offset
                # that was applied to the parent to preserve that relative position exactly.
                _, _, p_min_y, p_max_y = obj_verts[parent]
                parent_y_off = max_y_after[parent] - p_max_y
                target_min_y = min_y + parent_y_off
                logger.info(f"  {obj_name}: inside {parent}, parent_y_off={parent_y_off:.4f}, y=[{min_y:.4f},{max_y:.4f}] -> [{target_min_y:.4f},{max_y + parent_y_off:.4f}]")
            elif relation == "hang":
                # "hang": child top aligns with parent top + small clearance (child hangs from parent)
                # target: child_max_y = parent_max_y + 0.005
                # => y_offset = (max_y_after[parent] + 0.005) - max_y
                # => min_y after = min_y + y_offset = max_y_after[parent] + 0.005 - (max_y - min_y)
                target_max_y = max_y_after[parent] + 0.005
                y_offset = target_max_y - max_y
                write_obj_with_y_offset(output_path, lines, y_offset)
                max_y_after[obj_name] = target_max_y
                logger.info(f"  {obj_name}: hang from {parent}, top aligned: y=[{min_y:.4f},{max_y:.4f}] -> [{min_y + y_offset:.4f},{target_max_y:.4f}]")
                processed.add(obj_name)
                for child in children_map.get(obj_name, []):
                    if child not in processed:
                        queue.append(child)
                continue
            else:
                target_min_y = max_y_after[parent] + 0.005

            y_offset = target_min_y - min_y
            write_obj_with_y_offset(output_path, lines, y_offset)
            max_y_after[obj_name] = max_y + y_offset
            logger.info(f"  {obj_name}: parent={parent} ({relation}), y=[{min_y:.4f},{max_y:.4f}] -> [{target_min_y:.4f},{max_y + y_offset:.4f}]")
        else:
            # Parent unprocessed (unexpected): drop the object onto the floor
            y_offset = -min_y
            write_obj_with_y_offset(output_path, lines, y_offset)
            max_y_after[obj_name] = max_y + y_offset
            logger.info(f"  {obj_name}: parent={parent} (unprocessed), fallback to floor, y -> [0,{max_y + y_offset:.4f}]")

        processed.add(obj_name)

        for child in children_map.get(obj_name, []):
            if child not in processed:
                queue.append(child)

    # Determine ceiling height: take max over non-ceiling-child top points and the threshold
    # (ceiling children themselves are excluded to avoid a circular dependency)
    ceiling_children = set(children_map.get("ceiling", []))
    non_ceiling_max = max(
        (v for k, v in max_y_after.items() if k not in ceiling_children),
        default=0.0
    )
    ceiling_height = max(non_ceiling_max, ceiling_height_threshold)
    logger.info(f"\n  Non-ceiling scene max Y: {non_ceiling_max:.4f}, ceiling threshold: {ceiling_height_threshold:.4f}")
    logger.info(f"  Ceiling height: {ceiling_height:.4f}")

    # Pass 2c: shift ceiling children by ref_offset (same as wall children),
    # then push them down only if they overshoot ceiling_height (do not force-align to it).
    # This preserves relative height in the y-align coordinate frame and prevents the ceiling_height threshold
    # from pushing already-reasonable objects (e.g. a chandelier) too high.
    for obj_name in ceiling_children:
        if obj_name not in obj_verts:
            continue
        vertices, lines, min_y, max_y = obj_verts[obj_name]
        # Step 1: shift by ref_offset and clamp above the floor (same rule as wall children)
        y_offset = ref_offset + max(0.0, -(min_y + ref_offset))
        # Step 2: push down if any vertex still exceeds ceiling_height
        if max_y + y_offset > ceiling_height:
            y_offset = ceiling_height - max_y
            y_offset = max(y_offset, -min_y)  # clamp above floor again
        output_path = os.path.join(output_obj_canon_dir, f"scene_canon_{obj_name}.obj")
        write_obj_with_y_offset(output_path, lines, y_offset)
        max_y_after[obj_name] = max_y + y_offset
        logger.info(f"  {obj_name}: ceiling-ref_offset, y=[{min_y:.4f},{max_y:.4f}] -> [{min_y + y_offset:.4f},{max_y + y_offset:.4f}]")

    logger.info(f"  Processed {len(processed)} objects -> {output_obj_canon_dir}")

    return ceiling_height
